name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - "**" # deploy previews for all branches

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Pull Vercel project/environment settings
      - name: Pull Vercel environment info
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            npx vercel pull --yes --environment=production --token=$VERCEL_TOKEN
          else
            npx vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
          fi

      # 5. Build project
      - name: Build project
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            npx vercel build --prod --token=$VERCEL_TOKEN
          else
            npx vercel build --token=$VERCEL_TOKEN
          fi

      # 6. Deploy to Vercel
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            npx vercel deploy --prebuilt --prod --yes --token=$VERCEL_TOKEN
          else
            npx vercel deploy --prebuilt --yes --token=$VERCEL_TOKEN
          fi
