name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - "**"  # deploy all branches for previews

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy Preview or Production
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            vercel --prod --confirm --token=$VERCEL_TOKEN
          else
            vercel --prebuilt --confirm --token=$VERCEL_TOKEN
          fi
